// GENERATED by v2/tools/extract-content.mjs from the staging baseline.
// Do not edit by hand — edit the constants in staging:index.html and re-run.
// Source: origin/staging:index.html
import type { RawLevel, LevelDefaults } from '@core/types';

/** The four core actions, referenced by several campaign levels. */
export const CORE = ["talk","link","org","low"] as const;

/** Defaults merged UNDER each level: D = { ...PRO_DEFAULTS, ...LEVELS[i] }. */
export const PRO_DEFAULTS: LevelDefaults = {
  "winP": 0.1,
  "thresh": 0.55,
  "floorGain": 0.03,
  "crackP": 0,
  "crackR": 0.12,
  "surv": 85,
  "linkMax": 150,
  "waverAt": 0.5
};

/** Number of leading guided ("pro") levels. */
export const N_PRO = 6;

export const LEVELS: RawLevel[] = [
  {
    "pro": true,
    "name": "I · The kitchen table",
    "desc": "Learn to talk. Watch what spreads.",
    "N": 12,
    "rig": 0.35,
    "maxT": 12,
    "nInc": 0,
    "spies": 0,
    "reinforce": 0,
    "cracks": false,
    "allowed": [
      "talk"
    ],
    "obj": {
      "type": "aware",
      "count": 3,
      "lvl": 0.5,
      "text": "Help 3 neighbors see clearly (awareness above 50%)"
    },
    "intro": "Around this table, it is safe to speak. Click a neighbor, then Talk. Press Next turn and watch what you said travel along the lines between people — awareness flows on its own between connected neighbors."
  },
  {
    "pro": true,
    "name": "II · The block",
    "desc": "Some people are cut off. Reach them.",
    "N": 26,
    "rig": 0.5,
    "maxT": 16,
    "nInc": 0,
    "spies": 0,
    "reinforce": 0,
    "cracks": false,
    "twoClusters": true,
    "allowed": [
      "talk",
      "org",
      "link"
    ],
    "obj": {
      "type": "wins",
      "count": 1,
      "text": "Spark 1 structural win (a blue ripple)"
    },
    "intro": "Across the street lives a whole cluster no one here knows. Build a connection to bridge the gap, then organize until a whole circle sees clearly together — when that happens, a structural win sparks (a blue ripple): something concrete changes, fear drops, and what people remember rises. That ripple is how districts are won."
  },
  {
    "pro": true,
    "name": "III · The knock at the door",
    "desc": "They are watching now. Learn when to be quiet.",
    "N": 20,
    "rig": 0.62,
    "maxT": 10,
    "nInc": 1,
    "spies": 0,
    "reinforce": 0,
    "cracks": false,
    "scriptedCrack": 4,
    "allowed": [
      "talk",
      "org",
      "link",
      "low"
    ],
    "obj": {
      "type": "survive",
      "turn": 9,
      "count": 5,
      "lvl": 0.5,
      "text": "Survive past turn 8 with 5 people aware"
    },
    "intro": "Someone has been asking about you. On turn 4, they will come — you have been warned. Keep spreading the word, but when the amber circle appears, use Lay low until few eyes are on you."
  },
  {
    "pro": true,
    "name": "IV · The wall",
    "desc": "Some things speak while you sleep.",
    "N": 18,
    "rig": 0.55,
    "maxT": 12,
    "nInc": 0,
    "spies": 0,
    "reinforce": 0,
    "cracks": false,
    "allowed": [
      "talk",
      "link",
      "org",
      "mural",
      "post"
    ],
    "obj": {
      "type": "muralaware",
      "count": 5,
      "lvl": 0.5,
      "text": "Paint at least 1 mural and get 5 neighbors aware"
    },
    "intro": "Words fade when you stop speaking — but a wall does not sleep. Press Paint a mural, then click a spot inside your reach circle. Watch what it does turn after turn, without you. Try Post online too: it travels far and thin, and leaves a trace. Notice how the artist among your neighbors (stops to read every wall) responds to paint more than to talk."
  },
  {
    "pro": true,
    "name": "V · The witness",
    "desc": "Make their violence work against them.",
    "N": 20,
    "rig": 0.66,
    "maxT": 9,
    "nInc": 1,
    "spies": 0,
    "reinforce": 0,
    "cracks": false,
    "scriptedCrack": 5,
    "allowed": [
      "talk",
      "org",
      "link",
      "low",
      "doc"
    ],
    "obj": {
      "type": "witness",
      "text": "Have your camera armed (Document injustice) when the turn-5 crackdown lands"
    },
    "intro": "They will come on turn 5 — that is certain. But this time you have a camera. Use Document injustice before they arrive, and when they come, the world will see it: the suppression fails, and what was meant to silence people wakes them instead. Timing a witness is one of the strongest moves in the game."
  },
  {
    "pro": true,
    "name": "VI · The uniform",
    "desc": "The pillars of power are people too.",
    "N": 16,
    "rig": 0.6,
    "maxT": 14,
    "nInc": 1,
    "spies": 0,
    "reinforce": 0,
    "cracks": false,
    "waverAt": 0.4,
    "clusterCenter": true,
    "surv": 70,
    "allowed": [
      "talk",
      "org",
      "link",
      "low",
      "reach"
    ],
    "obj": {
      "type": "defect",
      "text": "Convince the incumbent to walk away (1 defection)"
    },
    "intro": "One incumbent watches this whole block — you all live in their shadow. You cannot remove them, but you can surround them: raise the awareness of the people living closest to the red square until it turns amber — they are wavering, doubting. Then use Reach out to wavering. Working inside their surveillance zone raises the eyes on you, so use Lay low when it climbs. When they walk away, their courage will hand you energy back."
  },
  {
    "name": "1 · The village",
    "desc": "The core four actions. Put the loop together.",
    "N": 74,
    "rig": 0.66,
    "maxT": 34,
    "winP": 0.09,
    "thresh": 0.58,
    "floorGain": 0.036,
    "crackP": 0.09,
    "crackR": 0.12,
    "surv": 80,
    "linkMax": 150,
    "nInc": 4,
    "waverAt": 0.44,
    "spies": 0,
    "reinforce": 0,
    "allowed": [
      "talk",
      "link",
      "org",
      "low"
    ],
    "newActs": "Talk, Build a connection, Organize, Lay low — the core four. Awareness → blue ripples → less fear, more memory."
  },
  {
    "name": "2 · The town",
    "desc": "New tools: murals, posts, and letters.",
    "N": 74,
    "rig": 0.72,
    "maxT": 32,
    "winP": 0.075,
    "thresh": 0.62,
    "floorGain": 0.032,
    "crackP": 0.12,
    "crackR": 0.14,
    "surv": 90,
    "linkMax": 140,
    "nInc": 5,
    "waverAt": 0.48,
    "spies": 0,
    "reinforce": 0,
    "allowed": [
      "talk",
      "link",
      "org",
      "low",
      "mural",
      "post",
      "letter"
    ],
    "newActs": "NEW — Paint a mural (a wall that keeps speaking without you), Post online (far, thin, traceable), and Send a letter (connect with anyone, anywhere — thinner thread, small trace)."
  },
  {
    "name": "3 · The informant",
    "desc": "It hunts your work. New: expose & document.",
    "N": 74,
    "rig": 0.76,
    "maxT": 32,
    "winP": 0.06,
    "thresh": 0.64,
    "floorGain": 0.03,
    "crackP": 0.13,
    "crackR": 0.15,
    "surv": 95,
    "linkMax": 135,
    "nInc": 5,
    "waverAt": 0.5,
    "spies": 1,
    "reinforce": 0,
    "allowed": [
      "talk",
      "link",
      "org",
      "low",
      "mural",
      "post",
      "letter",
      "expose",
      "doc"
    ],
    "newActs": "NEW — Expose informant (needs trust 30+, informant in reach) and Document injustice (the next crackdown backfires)."
  },
  {
    "name": "4 · The district",
    "desc": "New: turn the uniforms. Defection unlocked.",
    "N": 74,
    "rig": 0.8,
    "maxT": 30,
    "winP": 0.055,
    "thresh": 0.66,
    "floorGain": 0.028,
    "crackP": 0.15,
    "crackR": 0.16,
    "surv": 100,
    "linkMax": 130,
    "nInc": 6,
    "waverAt": 0.52,
    "spies": 1,
    "reinforce": 0,
    "allowed": [
      "talk",
      "link",
      "org",
      "low",
      "mural",
      "post",
      "letter",
      "expose",
      "doc",
      "reach",
      "speak"
    ],
    "newActs": "NEW — Reach out to wavering (surround an incumbent with aware people until they turn amber, then ask them to walk away — success refunds energy, and doubt spreads to enforcers nearby) and Speak publicly (loud, wide, dangerous)."
  },
  {
    "name": "5 · The regime",
    "desc": "Win too fast and they send reinforcements.",
    "N": 74,
    "rig": 0.82,
    "maxT": 30,
    "winP": 0.05,
    "thresh": 0.67,
    "floorGain": 0.027,
    "crackP": 0.16,
    "crackR": 0.17,
    "surv": 105,
    "linkMax": 126,
    "nInc": 6,
    "waverAt": 0.54,
    "spies": 1,
    "reinforce": 2
  },
  {
    "name": "6 · The apparatus",
    "desc": "Two informants. The pillars must fall.",
    "N": 74,
    "rig": 0.85,
    "maxT": 30,
    "winP": 0.047,
    "thresh": 0.68,
    "floorGain": 0.026,
    "crackP": 0.17,
    "crackR": 0.18,
    "surv": 108,
    "linkMax": 122,
    "nInc": 7,
    "waverAt": 0.56,
    "spies": 2,
    "reinforce": 2
  },
  {
    "name": "7 · The capital",
    "desc": "Everything at once. Make losses stop mattering.",
    "N": 74,
    "rig": 0.88,
    "maxT": 28,
    "winP": 0.045,
    "thresh": 0.7,
    "floorGain": 0.025,
    "crackP": 0.19,
    "crackR": 0.19,
    "surv": 112,
    "linkMax": 118,
    "nInc": 8,
    "waverAt": 0.58,
    "spies": 2,
    "reinforce": 3
  }
];
