// GENERATED by v2/tools/extract-content.mjs from the staging baseline.
// Do not edit by hand — edit the constants in staging:index.html and re-run.
// Source: origin/staging:index.html
import type { Trait } from '@core/types';

export const NAMES: string[] = ["Rosa","Tomás","Marta","Luis","Carmen","Diego","Ana","Pablo","Lucía","Miguel","Elena","Javier","Sofía","Andrés","Valeria","Hugo","Camila","Rafael","Inés","Óscar","Paula","Emilio","Clara","Bruno","Alma","Simón","Nadia","Félix","Irene","Mateo","Julia","Ciro","Delia","Ramón","Alba","Teo","Vera","Nico","Pilar","Iván","Sara","León","Mía","Aldo","Rita","Gael","Noa","Dario","Lena","Omar","Berta","Elio","Fina","Gustavo","Hilda","Ismael","Juana","Kiko","Lidia","Marcos","Nuria","Otto","Perla","Quique","Renata","Saúl","Tania","Ulises","Violeta","Wilmer","Ximena","Yara","Zoe","Abel"];

export const ROLES: string[] = ["a nurse","a bus driver","a teacher","a baker","a student","a mechanic","a shopkeeper","a farmer","a musician","a carpenter","an electrician","a seamstress","a doctor","a waiter","a fisherman","a librarian","a barber","a street vendor","a welder","a cook","a painter","a pharmacist","a janitor","a taxi driver"];

export const STAKES: string[] = ["the clinic lost its funding last winter","their brother was taken years ago","the pension stopped coming","their daughter wants to leave the country","the shop was fined for nothing","they lost their job for asking questions","their street floods and no one comes","the school has no books this year","their rent doubled overnight","they saw something they were not supposed to see","their father built this neighborhood","they keep a photo of how things used to be","the harvest was confiscated","their best friend stopped speaking to them out of fear","the hospital sent them home untreated","they teach children to read in secret","their husband waits in a line every dawn","the music venue was shuttered","they remember when the square had another name","their savings became paper"];

export const TRAITS: Trait[] = [
  {
    "id": "talker",
    "hint": "listens best over coffee",
    "talkMul": 1.6,
    "orgMul": 1,
    "muralMul": 1,
    "postMul": 1
  },
  {
    "id": "gatherer",
    "hint": "comes alive in meetings",
    "talkMul": 1,
    "orgMul": 2,
    "muralMul": 1,
    "postMul": 1
  },
  {
    "id": "artist",
    "hint": "stops to read every wall",
    "talkMul": 1,
    "orgMul": 1,
    "muralMul": 3,
    "postMul": 1
  },
  {
    "id": "online",
    "hint": "never off their phone",
    "talkMul": 1,
    "orgMul": 1,
    "muralMul": 1,
    "postMul": 2.2
  },
  {
    "id": "wary",
    "hint": "trusts slowly, holds firmly",
    "talkMul": 0.55,
    "orgMul": 0.7,
    "muralMul": 1,
    "postMul": 0.6
  }
];
