#!/usr/bin/env node
// Content extraction — Decision 5 (docs/v2/ARCHITECTURE.md §7.5).
//
// Reads the game constants from the STABLE `staging` baseline (never the
// experimental PR #10) and emits typed content modules under v2/src/content/.
// This is the single documented, repeatable path for V2 content during the
// parity phase: constants are edited once in the staging baseline and
// re-extracted here, never hand-maintained in two places.
//
// Usage:
//   node v2/tools/extract-content.mjs            # from staging:index.html (git)
//   node v2/tools/extract-content.mjs <file>     # from an explicit file
//
// It parses the source only for the pure-literal `const` blocks it needs; it
// does not execute the game. RHS literals are evaluated in an isolated scope
// with CORE pre-bound (LEVELS references CORE / CORE.concat).

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = resolve(HERE, '../src/content');
const PINNED = resolve(HERE, '../test/golden/staging-index.html');
const GIT_BASELINE = 'origin/staging:index.html';

// Default: read the PINNED baseline snapshot so content and the golden oracle
// share one source of truth. `--from-git` refreshes from the live staging ref
// (use with `npm run refresh-baseline` to also re-pin the snapshot). An explicit
// file path argument overrides both.
function loadSource() {
  const arg = process.argv[2];
  if (arg && arg !== '--from-git') return readFileSync(arg, 'utf8');
  if (arg === '--from-git') {
    return execSync(`git show ${GIT_BASELINE}`, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
  }
  return readFileSync(PINNED, 'utf8');
}

// Extract the raw right-hand-side text of `const <name> = <RHS>;` by scanning
// with bracket/quote balancing so we stop at the correct terminating `;`.
function extractConstRHS(src, name) {
  const decl = new RegExp(`const\\s+${name}\\s*=`, 'g');
  const m = decl.exec(src);
  if (!m) throw new Error(`const ${name} not found in baseline`);
  let i = m.index + m[0].length;
  while (src[i] === ' ' || src[i] === '\n' || src[i] === '\r') i++;
  const start = i;
  let depth = 0;
  let quote = null;
  for (; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === '\\') { i++; continue; }
      if (c === quote) quote = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { quote = c; continue; }
    if (c === '[' || c === '{' || c === '(') depth++;
    else if (c === ']' || c === '}' || c === ')') depth--;
    else if (c === ';' && depth === 0) break;
  }
  return src.slice(start, i).trim();
}

function evalLiteral(rhs, scope = {}) {
  const keys = Object.keys(scope);
  const vals = keys.map((k) => scope[k]);
  // eslint-disable-next-line no-new-func
  return new Function(...keys, `"use strict";return (${rhs});`)(...vals);
}

const src = loadSource();

const CORE = evalLiteral(extractConstRHS(src, 'CORE'));
const NAMES = evalLiteral(extractConstRHS(src, 'NAMES'));
const ROLES = evalLiteral(extractConstRHS(src, 'ROLES'));
const STAKES = evalLiteral(extractConstRHS(src, 'STAKES'));
const TRAITS = evalLiteral(extractConstRHS(src, 'TRAITS'));
const PRO_DEFAULTS = evalLiteral(extractConstRHS(src, 'PRO_DEFAULTS'));
const N_PRO = evalLiteral(extractConstRHS(src, 'N_PRO'));
const LEVELS = evalLiteral(extractConstRHS(src, 'LEVELS'), { CORE });

const banner = (extra = '') =>
  `// GENERATED by v2/tools/extract-content.mjs from the staging baseline.\n` +
  `// Do not edit by hand — edit the constants in staging:index.html and re-run.\n` +
  `// Source: staging baseline (${GIT_BASELINE}), pinned at v2/test/golden/staging-index.html\n${extra}\n`;

mkdirSync(CONTENT_DIR, { recursive: true });

const peopleTs =
  banner(`import type { Trait } from '@core/types';`) +
  `\nexport const NAMES: string[] = ${JSON.stringify(NAMES)};\n\n` +
  `export const ROLES: string[] = ${JSON.stringify(ROLES)};\n\n` +
  `export const STAKES: string[] = ${JSON.stringify(STAKES)};\n\n` +
  `export const TRAITS: Trait[] = ${JSON.stringify(TRAITS, null, 2)};\n`;

const levelsTs =
  banner(`import type { RawLevel, LevelDefaults } from '@core/types';`) +
  `\n/** The four core actions, referenced by several campaign levels. */\n` +
  `export const CORE = ${JSON.stringify(CORE)} as const;\n\n` +
  `/** Defaults merged UNDER each level: D = { ...PRO_DEFAULTS, ...LEVELS[i] }. */\n` +
  `export const PRO_DEFAULTS: LevelDefaults = ${JSON.stringify(PRO_DEFAULTS, null, 2)};\n\n` +
  `/** Number of leading guided ("pro") levels. */\n` +
  `export const N_PRO = ${JSON.stringify(N_PRO)};\n\n` +
  `export const LEVELS: RawLevel[] = ${JSON.stringify(LEVELS, null, 2)};\n`;

writeFileSync(resolve(CONTENT_DIR, 'people.ts'), peopleTs);
writeFileSync(resolve(CONTENT_DIR, 'levels.ts'), levelsTs);

console.log(
  `extracted: ${NAMES.length} names, ${ROLES.length} roles, ${STAKES.length} stakes, ` +
    `${TRAITS.length} traits, ${LEVELS.length} levels (N_PRO=${N_PRO}). ` +
    `Wrote people.ts, levels.ts.`,
);
